### ISSUE TITLE
Included vcpkg does not work on fresh Ubuntu installations

### ISSUE THREAD

**Issue by MatthiasHertel80** [ARM-software/vscode-environment-manager#12]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu Linux 24.04 x86 and Arm64
- VS Code Version: 1.96.4
- Extension Version: 1.10.0

The included vcpkg cannot run on an off-the-shelf installation of Ubuntu and VSCode.
 
It will fail with the first activation of the tools environment, with the following message:
**[00:00.142] Acquire 'bcee2a60-registry.zip': checking remote connections
failed to download from https://github.com/microsoft/vcpkg-ce-catalog/archive/refs/heads/main.zip
{}
failed to download /home/parallels/.vcpkg/downloads/bcee2a60-registry.zip from any source
environment-manager.activeConfigurationPaths
[
	[
		"/home/parallels/Documents/mlek-cmsis-pack-examples-main/vcpkg-configuration.json",
		"failed"
	]
]**

A local newer version of vpckg does not have these problem. It seems to depend less on existing system tools.

**Comment by thegecko** [comment]
Thanks for raising this issue.

As a workaround, you can use a newer vcpkg version by installing it and setting the `vcpkg` path in the VS Code settings.

**Comment by chentang16** [comment]
I met the same issue yesterday. Installing curl in your fresh ubuntu should resolve this issue

**Comment by MatthiasHertel80** [comment]
> I met the same issue yesterday. Installing curl in your fresh ubuntu should resolve this issue

This seems to work on the x86 variant only.

**Comment by MatthiasHertel80** [comment]
The issue still exists on Arm64 machines. If you look at the binary installed by https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.sh, you will see that this fixes this issue.

**Comment by MatthiasHertel80** [comment]
What MS releases is found on a different repo, here: https://github.com/microsoft/vcpkg-tool/releases
